sudo: required
services:
  - docker

install:
  - echo "${TRAVIS_BRANCH}"
  - docker build -t alephdata/aleph-convert-document:latest .

script:
  - sleep 1

after_success:
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push alephdata/aleph-convert-document:latest;
      docker tag alephdata/aleph-convert-document:latest alephdata/aleph-convert-document:$TRAVIS_TAG ;
      docker push alephdata/aleph-convert-document:$TRAVIS_TAG ;
    fi
