name: build

on:
  push:
    branch: master
  schedule:
  - cron:  '* 4 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Build docker image
      run: |
        docker build -t alephdata/convert-document:${GITHUB_SHA} .
    - name: Push docker image (master)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker push alephdata/convert-document:${GITHUB_SHA}
